line-length = 88
indent-width = 4

target-version = "py312"

[lint]
select = ["ANN", "B", "C4", "E", "F", "I", "Q", "W", "YTT"]

[lint.per-file-ignores]
"tests/*" = ["ANN"]

[lint.isort]
known-third-party = ["nuitka"]

[format]
quote-style = "double"
indent-style = "space"
