name: Validate Code

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install Validate Dependencies
        run: |
          pip install -r requirements_dev.txt
          sudo apt-get install libturbojpeg0-dev -y
          make build-all

      - name: Validate Config.ini Schema
        run: python ./config_schema_validator.py

      - name: Validate
        run: make validate

      - name: Install Dependencies
        run: pip install -r requirements.txt

        # xvfb enables tkinter in these tests
      - name: Unit Tests
        run: |
          export DISPLAY=:99
          Xvfb :99 &
          make test
          make test-memory-leak
